name: 🚀 Deploy to hosting

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    - name: 📂 Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ./
        state-name: .htautodeploystate
        server: sl1066.web.hostpoint.ch
        port: 21
        username: git@php-shop-tbz.david-abderhalden.ch
        password: ${{ secrets.FTP_PASSWORD }}
